apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres-chart.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "postgres-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "postgres-chart.name" . }}
    spec:
      containers:
        - name: vdt-db
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim