apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-chart.name" . }}
  labels:
    app: {{ include "postgres-chart.name" . }}
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: {{ include "postgres-chart.name" . }}
