apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-chart.fullname" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: postgres
